#!/usr/bin/env bash
# SSH hardening: sshd_config drop-in, service restart, fail2ban

configure_ssh() {
    is_done "ssh_config" && { log_info "SSH config: already hardened, skipping"; return; }

    local ssh_port="${SETUP_SSH_PORT:-22}"
    local permit_root="${SETUP_SSH_PERMIT_ROOT_LOGIN:-no}"
    local password_auth="${SETUP_SSH_PASSWORD_AUTH:-yes}"
    local max_auth_tries="${SETUP_SSH_MAX_AUTH_TRIES:-3}"
    local login_grace="${SETUP_SSH_LOGIN_GRACE_TIME:-30}"
    local allowed_users="${SETUP_SSH_ALLOWED_USERS:-}"
    local harden_ciphers="${SETUP_SSH_HARDEN_CIPHERS:-yes}"

    local dropin_dir="/etc/ssh/sshd_config.d"
    local dropin_file="${dropin_dir}/99-hardened.conf"

    log_info "Configuring SSH hardening (port: ${ssh_port}, password auth: ${password_auth})"

    # Use drop-in file if sshd_config includes the .d directory
    # Otherwise fall back to editing the main config directly
    if grep -q "^Include /etc/ssh/sshd_config.d/" /etc/ssh/sshd_config 2>/dev/null; then
        mkdir -p "$dropin_dir"
        _write_ssh_dropin "$dropin_file" "$ssh_port" "$permit_root" \
            "$password_auth" "$max_auth_tries" "$login_grace" \
            "$allowed_users" "$harden_ciphers"
    else
        log_warn "sshd_config.d not supported, editing /etc/ssh/sshd_config directly"
        cp /etc/ssh/sshd_config "/etc/ssh/sshd_config.bak.$(date +%s)"
        _apply_ssh_settings_sed "$ssh_port" "$permit_root" "$password_auth" \
            "$max_auth_tries" "$login_grace"
    fi

    # Test config BEFORE restarting — a bad config would disconnect everyone
    log_info "Testing sshd config..."
    if ! sshd -t; then
        log_error "sshd config test FAILED. Reverting drop-in."
        [[ -f "$dropin_file" ]] && rm -f "$dropin_file"
        log_error "SSH hardening NOT applied. Please check your config."
        exit 1
    fi

    log_info "sshd config test passed. Restarting sshd..."
    # Ubuntu uses "ssh", RHEL/CentOS uses "sshd"
    local ssh_svc
    if systemctl list-units --full -all 2>/dev/null | grep -q "ssh.service"; then
        ssh_svc="ssh"
    else
        ssh_svc="sshd"
    fi
    systemctl restart "$ssh_svc"

    mark_done "ssh_config"
    log_info "SSH hardened. Port: ${ssh_port}"
}

_write_ssh_dropin() {
    local file="$1"
    local port="$2"
    local permit_root="$3"
    local password_auth="$4"
    local max_auth_tries="$5"
    local login_grace="$6"
    local allowed_users="$7"
    local harden_ciphers="$8"

    cat > "$file" << EOF
# SSH hardening — generated by server-setup script
# Managed file: do not edit manually

Port ${port}
Protocol 2

PermitRootLogin ${permit_root}
PasswordAuthentication ${password_auth}
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys

PermitEmptyPasswords no
ChallengeResponseAuthentication no
KbdInteractiveAuthentication no
UsePAM yes

X11Forwarding no
PrintMotd no
AllowAgentForwarding no
AllowTcpForwarding no

MaxAuthTries ${max_auth_tries}
LoginGraceTime ${login_grace}
ClientAliveInterval 300
ClientAliveCountMax 2
MaxStartups 10:30:60
EOF

    if [[ -n "$allowed_users" ]]; then
        echo "AllowUsers ${allowed_users}" >> "$file"
    fi

    if [[ "$harden_ciphers" == "yes" ]]; then
        cat >> "$file" << 'EOF'

# Disable weak cryptographic algorithms
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
EOF
    fi
}

_apply_ssh_settings_sed() {
    local port="$1"
    local permit_root="$2"
    local password_auth="$3"
    local max_auth_tries="$4"
    local login_grace="$5"
    local config="/etc/ssh/sshd_config"

    _sshd_set "$config" "Port" "$port"
    _sshd_set "$config" "PermitRootLogin" "$permit_root"
    _sshd_set "$config" "PasswordAuthentication" "$password_auth"
    _sshd_set "$config" "MaxAuthTries" "$max_auth_tries"
    _sshd_set "$config" "LoginGraceTime" "$login_grace"
    _sshd_set "$config" "X11Forwarding" "no"
    _sshd_set "$config" "PermitEmptyPasswords" "no"
}

_sshd_set() {
    local file="$1" key="$2" value="$3"
    if grep -qE "^#?${key}\s" "$file"; then
        sed -i "s|^#\?${key}\s.*|${key} ${value}|" "$file"
    else
        echo "${key} ${value}" >> "$file"
    fi
}

configure_fail2ban() {
    is_done "fail2ban" && { log_info "fail2ban: already configured, skipping"; return; }

    if ! command -v fail2ban-server &>/dev/null; then
        log_warn "fail2ban not installed, installing now"
        apt_install fail2ban
    fi

    local ssh_port="${SETUP_SSH_PORT:-22}"

    log_info "Configuring fail2ban jail for SSH (port: ${ssh_port})"

    cat > /etc/fail2ban/jail.local << EOF
[DEFAULT]
# Ban for 1 hour by default
bantime  = 3600
# Window to detect repeated failures
findtime = 600
maxretry = 5
# Use systemd journal backend (works on modern Ubuntu)
backend = systemd

[sshd]
enabled  = true
port     = ${ssh_port}
logpath  = %(sshd_log)s
backend  = %(sshd_backend)s
maxretry = 3
# Extended ban for SSH: 24 hours
bantime  = 86400
EOF

    systemctl enable --now fail2ban
    systemctl restart fail2ban

    mark_done "fail2ban"
    log_info "fail2ban configured and running"
}
