#!/usr/bin/env bash
# System identity and resources: hostname, timezone, locale, NTP, swap, sysctl

setup_hostname() {
    is_done "hostname" && { log_info "hostname: already configured, skipping"; return; }

    log_info "Setting hostname to: ${SETUP_HOSTNAME}"
    hostnamectl set-hostname "${SETUP_HOSTNAME}"

    # Update /etc/hosts to map new hostname to 127.0.1.1
    # Without this, sudo warns "unable to resolve host"
    if grep -q "^127\.0\.1\.1" /etc/hosts; then
        sed -i "s/^127\.0\.1\.1.*/127.0.1.1\t${SETUP_HOSTNAME}/" /etc/hosts
    else
        echo -e "127.0.1.1\t${SETUP_HOSTNAME}" >> /etc/hosts
    fi

    mark_done "hostname"
    log_info "Hostname set to: $(hostname)"
}

setup_timezone() {
    is_done "timezone" && { log_info "timezone: already configured, skipping"; return; }

    log_info "Setting timezone to: ${SETUP_TIMEZONE}"
    timedatectl set-timezone "${SETUP_TIMEZONE}"
    mark_done "timezone"
    log_info "Timezone: $(timedatectl show --property=Timezone --value)"
}

setup_locale() {
    is_done "locale" && { log_info "locale: already configured, skipping"; return; }

    local locale="${SETUP_LOCALE:-en_US.UTF-8}"
    log_info "Generating locale: ${locale}"

    apt_install locales
    locale-gen "${locale}"
    update-locale LANG="${locale}" LC_ALL="${locale}"

    mark_done "locale"
    log_info "Locale configured: ${locale}"
}

setup_ntp() {
    is_done "ntp" && { log_info "ntp: already configured, skipping"; return; }

    log_info "Configuring NTP with chrony"
    apt_install chrony
    systemctl enable --now chrony
    timedatectl set-ntp true

    mark_done "ntp"
    log_info "NTP configured, time sync active"
}

setup_swap() {
    local size_gb="${SETUP_SWAP_SIZE_GB:-2}"
    local swappiness="${SETUP_SWAP_SWAPPINESS:-10}"

    if [[ "$size_gb" == "0" ]]; then
        log_info "Swap: SETUP_SWAP_SIZE_GB=0, skipping"
        return
    fi

    is_done "swap" && { log_info "swap: already configured, skipping"; return; }

    # Check if swapfile already active
    if swapon --show | grep -q '/swapfile'; then
        log_info "Swap already active, skipping creation"
        mark_done "swap"
        return
    fi

    log_info "Creating ${size_gb}GB swapfile (prevents OOM during apt upgrade on small VPS)"
    fallocate -l "${size_gb}G" /swapfile
    chmod 600 /swapfile
    mkswap /swapfile
    swapon /swapfile

    # Persist across reboots
    if ! grep -q '/swapfile' /etc/fstab; then
        echo '/swapfile none swap sw 0 0' >> /etc/fstab
    fi

    log_info "Swap active: $(free -h | grep Swap)"
    mark_done "swap"
}

apply_sysctl() {
    is_done "sysctl" && { log_info "sysctl: already applied, skipping"; return; }

    local sysctl_file="/etc/sysctl.d/99-server-hardening.conf"
    log_info "Applying sysctl hardening → ${sysctl_file}"

    local swappiness="${SETUP_SWAP_SWAPPINESS:-10}"

    cat > "$sysctl_file" << EOF
# Server hardening — generated by server-setup script

# Swap aggressiveness (lower = prefer RAM over swap)
vm.swappiness = ${swappiness}
vm.vfs_cache_pressure = 50

# IP spoofing protection
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Ignore ICMP broadcast requests
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Disable source packet routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# Ignore ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0

# Disable send redirects
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# SYN flood protection
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 5

# Log martian packets (source-routed packets)
net.ipv4.conf.all.log_martians = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Disable IPv6 router advertisements
net.ipv6.conf.all.accept_ra = 0
net.ipv6.conf.default.accept_ra = 0
EOF

    sysctl --system > /dev/null
    mark_done "sysctl"
    log_info "sysctl hardening applied"
}
