#!/usr/bin/env bash
# User management: create user, sudo, SSH key, default shell

create_user() {
    is_done "create_user" && { log_info "user: already created, skipping"; return; }

    local username="${SETUP_NEW_USER}"

    if id "$username" &>/dev/null; then
        log_info "User '${username}' already exists, skipping creation"
    else
        log_info "Creating user: ${username}"
        adduser --disabled-password --gecos "" "$username"
    fi

    # Add to sudo group
    usermod -aG sudo "$username"
    log_info "User '${username}' added to sudo group"

    mark_done "create_user"
}

configure_user_shell() {
    is_done "user_shell" && { log_info "user shell: already configured, skipping"; return; }

    local username="${SETUP_NEW_USER}"
    local shell="${SETUP_NEW_USER_SHELL:-bash}"
    local shell_path

    case "$shell" in
        fish)
            # fish must already be installed by packages.sh optional install
            if ! command -v fish &>/dev/null; then
                log_warn "fish not found, installing now"
                apt_install fish
            fi
            shell_path=$(command -v fish)
            _setup_fish_config "$username"
            ;;
        bash|*)
            shell_path=$(command -v bash)
            ;;
    esac

    chsh -s "$shell_path" "$username"
    mark_done "user_shell"
    log_info "Default shell for '${username}' set to: ${shell_path}"
}

_setup_fish_config() {
    local username="$1"
    local home_dir
    home_dir=$(getent passwd "$username" | cut -d: -f6)
    local fish_config_dir="${home_dir}/.config/fish"

    mkdir -p "$fish_config_dir"
    cat > "${fish_config_dir}/config.fish" << 'EOF'
# Fish shell config — generated by server-setup
if status is-interactive
    # Add /usr/local/bin to path if not present
    fish_add_path /usr/local/bin
end
EOF

    chown -R "${username}:${username}" "${home_dir}/.config"
    log_info "fish config created at ${fish_config_dir}/config.fish"
}

install_ssh_key() {
    local key="${SETUP_SSH_PUBLIC_KEY:-}"

    if [[ -z "$key" || "$key" == "ssh-ed25519 AAAA..." || "$key" == "YOUR_PUBLIC_KEY_HERE" ]]; then
        log_warn "No SSH public key configured — skipping authorized_keys setup"
        return
    fi

    is_done "ssh_key" && { log_info "ssh key: already installed, skipping"; return; }

    local username="${SETUP_NEW_USER}"
    local home_dir
    home_dir=$(getent passwd "$username" | cut -d: -f6)
    local ssh_dir="${home_dir}/.ssh"
    local auth_keys="${ssh_dir}/authorized_keys"

    log_info "Installing SSH public key for user: ${username}"

    install -d -m 700 -o "$username" -g "$username" "$ssh_dir"

    # Append key only if not already present
    if [[ -f "$auth_keys" ]] && grep -qF "$key" "$auth_keys"; then
        log_info "SSH key already present in authorized_keys"
    else
        echo "$key" >> "$auth_keys"
        log_info "SSH key added to ${auth_keys}"
    fi

    chmod 600 "$auth_keys"
    chown "${username}:${username}" "$auth_keys"

    mark_done "ssh_key"
}

harden_root() {
    [[ "${SETUP_DISABLE_ROOT_LOGIN:-yes}" != "yes" ]] && {
        log_info "Root login: keeping enabled (SETUP_DISABLE_ROOT_LOGIN != yes)"
        return
    }

    is_done "root_hardening" && { log_info "root hardening: already done, skipping"; return; }

    log_info "Locking root password (passwd -l root)"
    # Locks the password hash — root can still be accessed via console/rescue mode
    passwd -l root

    mark_done "root_hardening"
    log_info "Root password locked. Use '${SETUP_NEW_USER}' account with sudo."
}
